version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps
    steps:
      - checkout
      - run: mkdir -p ~/test-results/kaocha
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: clojure -A:dev:test -Spath
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run: clojure -A:dev:test -m kaocha.runner --reporter kaocha.report/documentation --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results
